import sys
import os
import subprocess
from llama_cpp import Llama

def run_nand_observation():
    print("=== TSFi DeepSeek NAND Observation Link ===", flush=True)
    gguf_path = "assets/DeepSeek-Coder-6.7B.gguf"
    
    if not os.path.exists(gguf_path):
        print("[FRACTURE] DeepSeek model not found.")
        return

    # 1. Execute the physical simulation
    print("-> Sourcing physical NAND trap outcome...", flush=True)
    sim_result = subprocess.run("./bin/test_nand_trap_sim", shell=True, capture_output=True, text=True)
    physical_log = sim_result.stdout.strip()
    
    print("-> Booting Vulkan DeepSeek Core for Observation...", flush=True)
    llm = Llama(
        model_path=gguf_path,
        n_ctx=4096,
        n_threads=16,
        n_gpu_layers=-1,
        verbose=False
    )

    prompt = f"""You are a Systems Architect.
Observe the following stdout trace generated by a C simulation of an SR NAND Latch being forced into a race condition (0,0 released to 1,1).

```text
{physical_log}
```

Based strictly on this physical observation, answer this single question in one sentence:
Does this simulation produce cryptographic entropy, or does it produce deterministic oscillation?
"""
    formatted_prompt = f"### Instruction:\\n{prompt}\\n### Response:\\n"

    print("\\n-> Forcing DeepSeek to Observe the Matrix...", flush=True)
    output = llm(
        formatted_prompt,
        max_tokens=64,
        stop=["### Instruction:"],
        echo=False
    )

    report = output['choices'][0]['text'].strip()
    print(f"\\n[DEEPSEEK OBSERVATION]\\n{report}\\n")

if __name__ == "__main__":
    run_nand_observation()
