import sys
import os
import subprocess
import time
from llama_cpp import Llama

def run_dual_observer():
    print("=== TSFi Dual-Observer Helmholtz Lock: NAND Trap ===", flush=True)
    gguf_path = "assets/DeepSeek-Coder-6.7B.gguf"
    manifold_path = "audit_lore.pos"
    
    if not os.path.exists(gguf_path):
        print("[FRACTURE] DeepSeek model not found.")
        return

    # 1. Primary Observer (The C Hardware Simulator)
    print("\\n[PRIMARY OBSERVER] Executing C NAND Simulation...", flush=True)
    sim_result = subprocess.run("./bin/test_nand_trap_sim", shell=True, capture_output=True, text=True)
    physical_log = sim_result.stdout.strip()
    
    # Extract the hardware's conclusion
    hw_conclusion = "Unknown"
    for line in physical_log.split('\\n'):
        if "[OUTCOME OBSERVED]" in line:
            hw_conclusion = line.split("]")[1].strip()
            break
            
    print(f"-> Hardware Conclusion: '{hw_conclusion}'")
    
    # Anchor Hardware Observation to Leaf 100
    safe_hw = hw_conclusion.replace('"', "'").replace('\\n', ' ')[:512]
    cmd_hw = f"./tsfi_helmholtz_cli post_lore {manifold_path} 100 \"PRIMARY_OBSERVER [C_SIM]: {safe_hw}\""
    subprocess.run(cmd_hw, shell=True, capture_output=True)
    print(f"   [ANCHOR] Primary Observation mathematically locked into Leaf 100.")

    # 2. Secondary Observer (DeepSeek Neural Matrix)
    print("\\n[SECONDARY OBSERVER] Booting Vulkan DeepSeek Core...", flush=True)
    llm = Llama(
        model_path=gguf_path,
        n_ctx=4096,
        n_threads=16,
        n_gpu_layers=-1,
        verbose=False
    )

    prompt = f"""You are a strict TSFi Architectural Auditor.
Observe the following stdout trace generated by a C simulation of an SR NAND Latch being forced into a race condition (0,0 released to 1,1).

```text
{physical_log}
```

Based strictly on this physical observation, answer this single question in one sentence:
Does this simulation produce cryptographic entropy, or does it produce deterministic oscillation?
"""
    formatted_prompt = f"### Instruction:\\n{prompt}\\n### Response:\\n"

    print("\\n-> Forcing DeepSeek to Observe the Matrix...", flush=True)
    output = llm(
        formatted_prompt,
        max_tokens=64,
        stop=["### Instruction:"],
        echo=False
    )

    ds_conclusion = output['choices'][0]['text'].strip()
    print(f"-> DeepSeek Conclusion: '{ds_conclusion}'")

    # Anchor DeepSeek Observation to Leaf 101
    safe_ds = ds_conclusion.replace('"', "'").replace('\\n', ' ')[:512]
    cmd_ds = f"./tsfi_helmholtz_cli post_lore {manifold_path} 101 \"SECONDARY_OBSERVER [AI]: {safe_ds}\""
    subprocess.run(cmd_ds, shell=True, capture_output=True)
    print(f"   [ANCHOR] Secondary Observation mathematically locked into Leaf 101.")

    # 3. Acoustic Collapse (Compute Helmholtz Root)
    print("\\n[ACOUSTIC STATE COLLAPSE] Crushing Observations via Keccak-512...", flush=True)
    inspect_result = subprocess.run(f"./tsfi_helmholtz_cli inspect {manifold_path}", shell=True, capture_output=True, text=True)

    for line in inspect_result.stdout.split('\\n'):
        if "State Root" in line:
            print(f"==================================================")
            print(f"   BIJECTIVE HELMHOLTZ ROOT ESTABLISHED")
            print(f"   {line.strip()}")
            print(f"==================================================")
            break

if __name__ == "__main__":
    run_dual_observer()
