import sys
import os
import re

def compile_tsfi_to_c(input_file, output_file):
    print(f"=== TSFi Fortran-like Compiler (tsfic) v1.2 ===")
    
    if not os.path.exists(input_file):
        print(f"[FRACTURE] Source file not found: {input_file}")
        sys.exit(1)
        
    with open(input_file, 'r') as f:
        lines = f.readlines()
        
    c_code = []
    c_code.append("// AUTO-GENERATED BY TSFIC COMPILER (STANDARD COMPLIANT)")
    c_code.append("#define _GNU_SOURCE")
    c_code.append("#include <stdio.h>")
    c_code.append("#include <stdlib.h>")
    c_code.append("#include <stdint.h>")
    c_code.append("#include <stdbool.h>")
    c_code.append("#include <string.h>")
    c_code.append("#include \"tsfi_merkle.h\"")
    c_code.append("#include \"tsfi_wavelet_arena.h\"")
    c_code.append("#include \"tsfi_svdag.h\"")
    c_code.append("#include \"lau_registry.h\"")
    c_code.append("#include \"tsfi_liang_barsky.h\"")
    c_code.append("")
    
    in_program = False
    current_arena = "TEST_ARENA" # Track the last declared arena
    
    for line in lines:
        line = line.strip()
        if not line or line.startswith("!"):
            continue
            
        tokens = line.split()
        cmd = tokens[0].upper()
        
        if cmd == "PROGRAM":
            in_program = True
            prog_name = tokens[1]
            c_code.append(f"int main(int argc, char **argv) {{")
            c_code.append(f"    (void)argc; (void)argv;")
            c_code.append(f'    printf("[TSFIC] Starting Program: {prog_name}\\n");')
            c_code.append(f"    uint64_t current_prime = 953473ULL;")
            c_code.append(f"    srand(42);")
            c_code.append(f"    uint8_t *physical_memory_block = malloc(1024 * 1024 * 4);")
            c_code.append(f"    memset(physical_memory_block, 0, 1024 * 1024 * 4);")
            
        elif cmd == "END":
            if len(tokens) > 1 and tokens[1].upper() == "PROGRAM":
                c_code.append(f'    printf("[TSFIC] Program Terminated Successfully.\\n");')
                c_code.append(f"    free(physical_memory_block);")
                c_code.append(f"    return 0;")
                c_code.append(f"}}")
                in_program = False

        elif cmd == "SET_PRIME":
            val = tokens[1]
            c_code.append(f"    current_prime = {val}ULL;")

        elif cmd == "ARENA":
            arena_name = tokens[1]
            current_arena = arena_name
            size = tokens[tokens.index("SIZE") + 1] if "SIZE" in tokens else tokens[2]
            c_code.append(f"    TsfiWaveletArena {arena_name};")
            c_code.append(f"    tsfi_wavelet_arena_init(&{arena_name}, physical_memory_block, {size});")
            
        elif cmd == "WAVELET":
            wavelet_name, arena_name = tokens[1], tokens[3]
            c_code.append(f"    TsfiWavelet *{wavelet_name} = tsfi_STAT(&{arena_name}, current_prime);")

        elif cmd == "AVAIL":
            wavelet_name, xi = tokens[1], tokens[2]
            c_code.append(f"    tsfi_Avail({wavelet_name}, {xi}, current_prime);")

        elif cmd == "FORM":
            target_name, source_name = tokens[1], tokens[2]
            c_code.append(f"    tsfi_Form({target_name}, {source_name}->telemetry.Fa.contour, current_prime);")

        elif cmd == "POLARIZE":
            wavelet_name = tokens[1]
            c_code.append(f"    tsfi_Polarize({wavelet_name}, current_prime);")

        elif cmd == "CONJUGATE":
            target_name, source_name = tokens[1], tokens[2]
            c_code.append(f"    tsfi_Conjugate({target_name}, {source_name}->telemetry.Fa.pole, current_prime);")

        elif cmd == "CONIFY":
            wavelet_name, pulse = tokens[1], tokens[2]
            c_code.append(f"    tsfi_Conify({wavelet_name}, {pulse}, current_prime);")

        elif cmd == "SATURATE":
            if len(tokens) == 4:
                rod, cone, pulse = tokens[1], tokens[2], tokens[3]
                c_code.append(f"    tsfi_Saturate({rod}, {pulse}, {cone}->telemetry.Fa.foundation, {cone}->telemetry.Fa.channel, current_prime);")
            else:
                target_name, source_name = tokens[1], tokens[2]
                c_code.append(f"    tsfi_Saturate({target_name}, 0, {source_name}->telemetry.Fa.foundation, {source_name}->telemetry.Fa.channel, current_prime);")

        elif cmd == "GENERATE":
            rod_name, cone_name, xi, alpha, beta = tokens[1], tokens[2], tokens[3], tokens[4], tokens[5]
            c_code.append(f"    tsfi_GENERATE({rod_name}, {cone_name}, {xi}, {alpha}, {beta}, current_prime);")

        elif "CREATE_YI" in line:
            parts = line.split("=")
            if len(parts) == 2:
                yi_name = parts[0].strip()
                tokens = parts[1].strip().split()
                rod_name, cone_name, xi, alpha, beta = tokens[1], tokens[2], tokens[3], tokens[4], tokens[5]
                c_code.append(f"    TsfiWavelet *{yi_name} = {rod_name};")
                c_code.append(f"    tsfi_CREATE_YI({rod_name}, {cone_name}, {xi}, {alpha}, {beta}, current_prime);")
            else:
                tokens = line.split()
                rod_name, cone_name, xi, alpha, beta = tokens[1], tokens[2], tokens[3], tokens[4], tokens[5]
                c_code.append(f"    tsfi_CREATE_YI({rod_name}, {cone_name}, {xi}, {alpha}, {beta}, current_prime);")

        elif cmd == "ATTACH_FIELD":
            name, type_val, field_name = tokens[1], tokens[2], tokens[3]
            value = " ".join(tokens[4:]).strip('"')
            c_code.append(f'    tsfi_AttachField({name}, "{type_val}", "{field_name}", "{value}");')

        elif cmd == "SEED_WAVELET":
            name, base, secret, signal = tokens[1], tokens[2], tokens[3], tokens[4]
            c_code.append(f"    {name}->telemetry.Fa.base = {base}ULL;")
            c_code.append(f"    {name}->telemetry.Fa.secret = {secret}ULL;")
            c_code.append(f"    {name}->telemetry.Fa.signal = {signal}ULL;")
            c_code.append(f"    tsfi_Tune({name}, current_prime);")

        elif cmd == "IONIZE":
            if len(tokens) == 3:
                w1, w2 = tokens[1], tokens[2]
                c_code.append(f"    tsfi_IONIZE_BOND({w1}, current_prime);")
                c_code.append(f"    tsfi_IONIZE_BOND({w2}, current_prime);")
            else:
                wavelet_name = tokens[1]
                c_code.append(f"    tsfi_IONIZE_BOND({wavelet_name}, current_prime);")

        elif cmd == "MAGNETIZE":
            rod_name, cone_name = tokens[1], tokens[2]
            c_code.append(f"    tsfi_MAGNETIZE_JOINT({rod_name}, {cone_name}, current_prime);")

        elif cmd == "SEAL_HEADER":
            name = tokens[1]
            c_code.append(f'    tsfi_SealHeader({name}, current_prime);')

        elif cmd == "ACTIVATE_YANG":
            name, epsilon = tokens[1], tokens[2]
            c_code.append(f'    tsfi_ActivateYang({name}, {epsilon}ULL, current_prime);')

        elif cmd == "EVOLVE_DAI":
            name, choice = tokens[1], tokens[2].upper()
            sel = 0 if choice == "ICHI" else 1
            c_code.append(f'    tsfi_EvolveDai({name}, {sel}, current_prime);')

        elif cmd == "PRINT_WAVELET":
            name = tokens[1]
            c_code.append(f'    tsfi_wavelet_print({name}, "{name}");')

        elif cmd == "REACT":
            rod_name, cone_name, pi = tokens[1], tokens[2], tokens[3]
            c_code.append(f"    {{ uint64_t ir, dr, ic, dc; tsfi_REACT_JOINT({rod_name}, {cone_name}, {pi}, &ir, &dr, &ic, &dc, current_prime);")
            c_code.append(f'      printf("[TSFIC] Reaction Quartet (Pi={pi}):\\n");')
            c_code.append(f'      printf("  Rod:  Ichidai=%llu, Daiichi=%llu\\n", (unsigned long long)ir, (unsigned long long)dr);')
            c_code.append(f'      printf("  Cone: Ichidai=%llu, Daiichi=%llu\\n", (unsigned long long)ic, (unsigned long long)dc); }}')

        elif cmd == "SVDAG":
            dag_name = tokens[1]
            cap = tokens[tokens.index("CAP") + 1] if "CAP" in tokens else tokens[2]
            c_code.append(f"    TSFiHelmholtzSVDAG *{dag_name} = tsfi_svdag_create({cap});")

        elif cmd == "ADD_OP":
            dag_name = tokens[1]
            op_type = tokens[tokens.index("TYPE") + 1]
            kernel = tokens[tokens.index("KERNEL") + 1]
            energy = tokens[tokens.index("ENERGY") + 1]
            freq = tokens[tokens.index("FREQ") + 1]
            c_code.append(f"    tsfi_svdag_add_operator({dag_name}, HELMHOLTZ_OP_{op_type}, {kernel}, {energy}, {freq});")

        elif cmd == "REDUCE":
            wavelet = tokens[1]
            level = tokens[tokens.index("LEVEL") + 1]
            epoch = tokens[tokens.index("EPOCH") + 1]
            resonance = tokens[tokens.index("RESONANCE") + 1]
            dag = tokens[tokens.index("DAG") + 1] if "DAG" in tokens else "NULL"
            
            c_code.append(f"    {{ uint8_t state_root[32], receipt_root[32];")
            c_code.append(f"      tsfi_helmholtz_reduce_{level}(state_root, receipt_root, NULL, NULL, physical_memory_block, {epoch}, {resonance}, {dag});")
            c_code.append(f"      printf(\"[TSFIC] Helmholtz Reduction (L{level}): \");")
            c_code.append(f"      for(int i=0; i<32; i++) printf(\"%02x\", state_root[i]); printf(\"\\n\"); }}")

        elif cmd == "SHEAF":
            sheaf_name = tokens[1]
            members = tokens[2:]
            member_list = ", ".join(members)
            c_code.append(f"    TsfiWavelet *w_list_{sheaf_name}[] = {{ {member_list} }};")
            c_code.append(f"    TsfiSheaf {sheaf_name};")
            c_code.append(f"    tsfi_CreateSheaf(&{sheaf_name}, w_list_{sheaf_name}, {len(members)});")

        elif cmd == "REDUCE_SHEAF":
            sheaf_name = tokens[1]
            c_code.append(f"    tsfi_ReduceSheaf(&{sheaf_name}, current_prime);")

        elif cmd == "PRINT_SHEAF":
            sheaf_name = tokens[1]
            c_code.append(f"    tsfi_sheaf_print(&{sheaf_name}, \"{sheaf_name}\");")

        elif cmd == "ALLOCATE_LAYERED_SHELL":
            wavelet_name = tokens[1]
            trait = tokens[2]
            size = int(tokens[3])
            c_code.append(f"    {{")
            c_code.append(f"      long req_size = {size};")
            c_code.append(f"      TSFI_WAVELET_ENFORCE_ARENA_BOUNDS(&{current_arena}, req_size);")
            c_code.append(f"      {wavelet_name}->file_cell.content_ptr = {current_arena}.base_ptr + {current_arena}.offset;")
            c_code.append(f"      {wavelet_name}->file_cell.content_size = req_size;")
            c_code.append(f"      {current_arena}.offset += req_size;")
            c_code.append(f"      {wavelet_name}->telemetry.trait = {trait};")
            c_code.append(f"      {wavelet_name}->telemetry.current_seal_level = 1; // Shell Allocated, pending content")
            c_code.append(f"      {wavelet_name}->state = 1;")
            c_code.append(f"      printf(\"[LIANG-BARSKY] Allocated Layered Shell of %ld bytes for Trait '%s'.\\n\", req_size, \"{trait}\");")
            c_code.append(f"    }}")
            
        elif cmd == "ALLOCATE_FILE_CONTENT":
            wavelet_name = tokens[1]
            file_path = " ".join(tokens[2:]).strip('"')
            c_code.append(f"    {{ FILE *f_alloc = fopen(\"{file_path}\", \"rb\");")
            c_code.append(f"      if (f_alloc) {{ fseek(f_alloc, 0, SEEK_END); long fsize = ftell(f_alloc); rewind(f_alloc);")
            c_code.append(f"        strncpy({wavelet_name}->file_cell.filename, \"{file_path}\", 31);")
            c_code.append(f"        TSFI_WAVELET_ENFORCE_ARENA_BOUNDS(&TEST_ARENA, fsize);")
            c_code.append(f"        {wavelet_name}->file_cell.content_ptr = TEST_ARENA.base_ptr + TEST_ARENA.offset;")
            c_code.append(f"        {wavelet_name}->file_cell.content_size = fsize;")
            c_code.append(f"        fread({wavelet_name}->file_cell.content_ptr, 1, fsize, f_alloc); fclose(f_alloc);")
            c_code.append(f"        TEST_ARENA.offset += fsize;")
            c_code.append(f"        {wavelet_name}->telemetry.trait = TSFI_TRAIT_FILE;")
            c_code.append(f"        {wavelet_name}->telemetry.current_seal_level = 2;")
            c_code.append(f"        {wavelet_name}->state = 1;")
            c_code.append(f"        printf(\"[SPIDER] Allocated %ld bytes from FORTRAN ARENA and filled Layer 2 for '%s'.\\n\", fsize, {wavelet_name}->file_cell.filename); }} }}")

        elif cmd == "AUDIT_SPIDER_TASTE":
            wavelet_name = tokens[1]
            c_code.append(f"    if (!tsfi_alligator_audit_spider_taste({wavelet_name})) {{")
            c_code.append(f"        printf(\"[FRACTURE] Spider failed the taste audit. Reaping.\\n\");")
            c_code.append(f"        return 1;")
            c_code.append(f"    }}")

        elif cmd == "ATTACH_DATA":
            wavelet_name = tokens[1]
            data = " ".join(tokens[2:]).strip('"')
            c_code.append(f'    strncpy((char*){wavelet_name}->payload, "{data}", 120);')

        elif cmd == "LOG_TELEMETRY":
            msg = " ".join(tokens[1:]).strip('"')
            c_code.append(f'    printf("[TELEMETRY] {msg}\\n");')

    with open(output_file, 'w') as f:
        f.write("\n".join(c_code))
        
    print(f"[PASS] Successfully transpiled {input_file} into {output_file}")
    
if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python3 tsfic_compiler.py <input.tsfi> <output.c>")
        sys.exit(1)
    compile_tsfi_to_c(sys.argv[1], sys.argv[2])
