/* Generated by Auncient usd_gen_schema tool. Do not edit. */
#ifndef AUNCIENT_CACTUS_SCHEMA_H
#define AUNCIENT_CACTUS_SCHEMA_H

#include <string.h>

typedef struct {
    float density;
    float stiffness;
    char texture[32];
} usd_auncient_cactus_schema_t;

static inline void usd_init_auncient_cactus_schema(usd_auncient_cactus_schema_t *schema) {
    schema->density = 1.00f;
    schema->stiffness = 0.50f;
    strcpy(schema->texture, "cloth");
}

#endif /* AUNCIENT_CACTUS_SCHEMA_H */
