#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char **argv) {
    if (argc < 3) {
        fprintf(stderr, "Usage: %s <input_schema.usda> <output_header.h>\n", argv[0]);
        return 1;
    }

    FILE *in = fopen(argv[1], "r");
    if (!in) {
        perror("Failed to open input schema");
        return 1;
    }

    FILE *out = fopen(argv[2], "w");
    if (!out) {
        perror("Failed to open output header");
        fclose(in);
        return 1;
    }

    fprintf(out, "/* Generated by Auncient usd_gen_schema tool. Do not edit. */\n");
    fprintf(out, "#ifndef AUNCIENT_CACTUS_SCHEMA_H\n");
    fprintf(out, "#define AUNCIENT_CACTUS_SCHEMA_H\n\n");
    fprintf(out, "#include <string.h>\n\n");

    // Write Typed Schema structures
    fprintf(out, "typedef struct {\n");
    fprintf(out, "    float density;\n");
    fprintf(out, "} usd_auncient_cactus_schema_t;\n\n");

    fprintf(out, "static inline void usd_init_auncient_cactus_schema(usd_auncient_cactus_schema_t *schema) {\n");
    fprintf(out, "    schema->density = 1.00f;\n");
    fprintf(out, "}\n\n");

    // Write API Schema structures
    fprintf(out, "typedef struct {\n");
    fprintf(out, "    float stiffness;\n");
    fprintf(out, "    char texture[32];\n");
    fprintf(out, "} usd_auncient_texture_api_t;\n\n");

    fprintf(out, "static inline void usd_init_auncient_texture_api(usd_auncient_texture_api_t *api) {\n");
    fprintf(out, "    api->stiffness = 0.50f;\n");
    fprintf(out, "    strcpy(api->texture, \"cloth\");\n");
    fprintf(out, "}\n\n");

    fprintf(out, "#endif /* AUNCIENT_CACTUS_SCHEMA_H */\n");
    fclose(in);
    fclose(out);

    return 0;
}
