#ifndef TSFI_FONT_SHAPING_H
#define TSFI_FONT_SHAPING_H

#include "tsfi_types.h"
#include <stdint.h>

typedef struct {
    float m11, m12; // Scale X, Skew Y
    float m21, m22; // Skew X, Scale Y
    float dx, dy;   // Translation (secret)
} tsfi_transform_t;

// A single shaped glyph, mapped as a WaveSystem entity so individual
// visual thunks (like per-character coloring or jitter) can be applied.
DEFINE_MAPPED_STRUCT(TSFiShapedGlyph,
    uint32_t glyph_index;
    uint32_t cluster_index; // Maps back to the original input string index
    
    // The exact 2D affine transformation applied to the glyph's local geometry.
    // This defines where and how the glyph is drawn relative to its parent cluster.
    tsfi_transform_t transform;
    
    // The internal advance of this specific glyph, used by linear shaping algorithms.
    float advance_dx;
    float advance_dy;
)

// A single orthographic syllable/molecule, mapped as a WaveSystem entity.
// This allows global thunks (like spinning a whole Marchen stack) to be applied
// to the entire visual group simultaneously.
DEFINE_MAPPED_STRUCT(TSFiShapeCluster,
    uint32_t script_id;       // e.g., TAG('m','a','r','c') for Marchen
    
    // The raw input sequence for this syllable
    uint32_t *codepoints;     
    int num_codepoints;

    // The output geometry generated by the shaping thunk (e.g., shape_marchen.c)
    TSFiShapedGlyph *glyphs;  
    int num_glyphs;

    // The global transform for the ENTIRE cluster.
    // Visual thunks modify this matrix to rotate/scale the whole syllable at once.
    tsfi_transform_t cluster_transform; 

    // The vector to advance the pen to the NEXT cluster.
    float advance_dx;
    float advance_dy;
)

// Main entry point for shaping text into clusters
int tsfi_font_shape_text(void *ot, const uint32_t *codepoints, int count, TSFiShapeCluster ***out_clusters);

// Free the allocated clusters and their internal glyph arrays
void tsfi_font_free_clusters(TSFiShapeCluster **clusters, int num_clusters);

#endif // TSFI_FONT_SHAPING_H
