#ifndef TSFI_CADE_IMF_H
#define TSFI_CADE_IMF_H

#include <stdint.h>
#include <stddef.h>

int tsfi_mf_cade_register_taxpayer(const char *ssn, double balance, int status, char *registry_out, int max_len);
int tsfi_mf_imf_process_transaction(const char *ssn, int transaction_code, double amount, double *balance_in_out, char *log_out, int max_len);
int tsfi_mf_cade_process_daily_batch(const char **ssns, const int *tcs, const double *amounts, int count, double *balances, char *batch_report, int max_len);
int tsfi_mf_imf_validate_transaction_code(int transaction_code, double amount, int *is_valid);
int tsfi_mf_imf_set_freeze_code(const char *ssn, char freeze_code, char *account_state, int max_len);
int tsfi_mf_imf_is_frozen(const char *account_state, int *is_frozen);
int tsfi_mf_cade_lookup_taxpayer(const char *ssn, const char *registry_pool, double *balance_out, int *status_out);
int tsfi_mf_imf_encode_cycle_code(int year, int week, int day, char *cycle_out, int max_len);
int tsfi_mf_imf_decode_cycle_code(const char *cycle_code, int *year, int *week, int *day);
int tsfi_mf_cade_update_taxpayer_status(char *registry_entry, int new_status);
int tsfi_mf_imf_parse_dln(const char *dln, int *site_code, int *tax_class, int *doc_code, int *julian_date, int *serial_num);
int tsfi_mf_cade_adjust_balance(char *registry_entry, double offset_amount);
int tsfi_mf_imf_generate_dln(int site_code, int tax_class, int doc_code, int julian_date, int serial_num, char *dln_out, int max_len);
int tsfi_mf_imf_get_tax_class_name(int tax_class, char *name_out, int max_len);
int tsfi_mf_imf_get_transaction_sign(int transaction_code, int *sign_out);
int tsfi_mf_imf_reconcile_balance(double initial_balance, const int *tcs, const double *amounts, int count, double final_balance, int *is_reconciled);
int tsfi_mf_imf_validate_dln(const char *dln, int *is_valid);
int tsfi_mf_cade_format_batch_summary(int processed, int errors, double total_debit, double total_credit, char *out_buf, int max_len);
int tsfi_mf_imf_get_doc_code_name(int doc_code, char *name_out, int max_len);
int tsfi_mf_cade_export_registry(const char *registry_pool, char *export_buf, int max_len);
int tsfi_mf_imf_validate_doc_code(int doc_code, int *is_valid);
int tsfi_mf_cade_compact_registry(char *registry_pool);
int tsfi_mf_imf_get_doc_code_by_name(const char *name, int *doc_code_out);
int tsfi_mf_cade_locate_record_offset(const char *ssn, const char *registry_pool, int *offset_out);
int tsfi_mf_cade_get_status_name(int status_code, char *name_out, int max_len);

int tsfi_mf_ddl_set_mode(int mode);
int tsfi_mf_ddl_execute(const char *statement, char *output, size_t out_len);
int tsfi_mf_dml_set_mode(int mode);
int tsfi_mf_dml_execute(const char *statement, char *output, size_t out_len);
int tsfi_mf_cade_verify_address(const char *addr_a, const char *addr_b, int *is_match);
int tsfi_mf_imf_get_cycle_week(const char *cycle_code, int *week_out);

int tsfi_mf_imf_verify_document_form(int doc_code, int target_code, int *result);
int tsfi_mf_cade_check_status_mask(int status_code, unsigned int mask, int *is_valid);
int tsfi_mf_cade_route_partition(const char *ssn, int *partition_out);
int tsfi_mf_imf_verify_ssn_check_digit(const char *ssn, int *is_valid);
int tsfi_mf_imf_evaluate_audit_discrepancy(double reported_income, double documented_income, int missing_schedules, int *audit_flag);
int tsfi_mf_imf_schedule_refund(const char *cycle_code, int transaction_code, char *schedule_date_out, int max_len);
int tsfi_mf_imf_apply_liability_offset(double refund_amt, double liability_amt, double *net_refund_out, double *remaining_liability_out);
int tsfi_mf_imf_verify_filing_status(int filing_status, int doc_code, int *is_allowed);
int tsfi_mf_cade_classify_batch_error(int error_code, char *severity_out, int max_len);
int tsfi_mf_imf_verify_agi_calculation(double gross_income, double adjustments, double reported_agi, int *is_match);
int tsfi_mf_imf_validate_deductions(int filing_status, double claimed_deductions, int use_itemized, int *is_valid);
int tsfi_mf_cade_check_refund_hold(int identity_verified, int address_verified, int *has_hold);
int tsfi_mf_imf_verify_signatures(int filing_status, int has_taxpayer_sig, int has_spouse_sig, int *is_valid);
int tsfi_mf_imf_check_dependent_duplicates(const char *primary_ssn, const char *secondary_ssn, const char **dep_ssns, int dep_count, int *has_duplicates);
int tsfi_mf_imf_verify_filing_deadline(int julian_date_filed, int has_approved_extension, int *is_timely);
int tsfi_mf_cade_route_refund_disbursement(const char *routing_number, const char *account_number, int *method_out);
int tsfi_mf_imf_verify_refund_threshold(double refund_amount, double limit, int *requires_review);
int tsfi_mf_cade_verify_prior_year_agi(double input_agi, double actual_prior_agi, int *is_match);
int tsfi_mf_imf_classify_agi_bracket(double agi, int *bracket_out);
int tsfi_mf_cade_verify_designee_record(int has_designee, const char *designee_pin, int *is_valid);
int tsfi_mf_cade_verify_filing_method(int method_code, int *is_valid);
int tsfi_mf_imf_check_first_time_filer(const char *ssn, const char *registry_pool, int *is_first_time);
int tsfi_mf_cade_verify_phone_area_code(const char *phone, const char *state_code, int *is_match);
int tsfi_mf_imf_verify_dependent_age(int birth_year, int tax_year, int *is_eligible);
int tsfi_mf_cade_verify_zip_state(const char *zip, const char *state_code, int *is_match);
int tsfi_mf_imf_verify_eitc_qualifying_child(const char *relationship, int residency_days, int *is_eligible);
int tsfi_mf_imf_verify_homebuyer_recapture(int acquisition_year, double credit_received, double *recapture_amount);
int tsfi_mf_cade_query_prior_refund_offset(const char *ssn, const char *offset_registry, double *offset_amount);
int tsfi_mf_cade_verify_ip_pin(const char *ip_pin, int *is_valid);
int tsfi_mf_imf_verify_single_standard_deduction(double claimed_deduction, int *is_valid);
int tsfi_mf_cade_verify_state_code(const char *state_code, int *is_valid);
int tsfi_mf_imf_verify_dependent_care_ceiling(int dependent_count, double claimed_expenses, int *is_valid);
int tsfi_mf_cade_verify_street_parity(const char *address, int *parity_out);
int tsfi_mf_imf_verify_student_loan_interest(double claimed_interest, int *is_valid);
int tsfi_mf_imf_verify_deduction_bonus(int over_65_count, int blind_count, int filing_status, double claimed_bonus, int *is_valid);
int tsfi_mf_cade_verify_ss_benefits(double modified_agi, double half_ss_benefits, double taxable_ss_reported, int filing_status, int *is_valid);
int tsfi_mf_cade_verify_signature_date(int sign_year, int tax_year, int *is_valid);
int tsfi_mf_imf_verify_qbi_threshold(double taxable_income, int filing_status, int *is_below_threshold);
int tsfi_mf_cade_verify_state_withholding(const char *state_code, double state_wages, double claimed_withholding, int *is_valid);
int tsfi_mf_imf_verify_k1_share(double partner_share_pct, double partnership_income, double reported_share_amt, int *is_valid);
int tsfi_mf_cade_verify_witness_indicator(int doc_code, int has_witness_sig, int *is_valid);
int tsfi_mf_imf_verify_actc_limit(int child_count, double claimed_actc, int *is_valid);
int tsfi_mf_cade_verify_filing_volume(const char *state_code, int current_count, int max_limit, int *is_allowed);
int tsfi_mf_imf_verify_first_time_address(const char *address, int *is_valid);
int tsfi_mf_imf_verify_federal_withholding_cap(double gross_income, double claimed_withholding, int *is_valid);
int tsfi_mf_imf_check_amt_threshold(double agi, int filing_status, int *requires_amt);
int tsfi_mf_imf_verify_social_security_tax_cap(double wages, double claimed_ss_withheld, int *is_valid);
int tsfi_mf_imf_verify_qualified_dividend_rate(double taxable_income, double qualified_dividends, double dividend_tax, int *is_valid);
int tsfi_mf_imf_check_se_tax_threshold(double net_profit, int *se_required);
int tsfi_mf_imf_check_niit_threshold(double magi, int filing_status, int *niit_required);
int tsfi_mf_imf_verify_medical_floor(double agi, double total_expenses, double claimed_deduction, int *is_valid);
int tsfi_mf_imf_verify_qbi_deduction(double qbi, double taxable_income, double claimed_qbi_deduction, int *is_valid);
int tsfi_mf_imf_select_deduction(double standard_ded, double itemized_ded, double claimed_ded, int *is_valid);
int tsfi_mf_imf_verify_charity_cap(double agi, double claimed_charity, int *is_valid);
int tsfi_mf_imf_verify_ptc_eligibility(double agi, double fpl_limit, int *is_eligible);
int tsfi_mf_imf_verify_foreign_tax_credit(double foreign_taxes_paid, double total_tax_liability, double claimed_credit, int *is_valid);
int tsfi_mf_imf_check_interest_limit_for_eitc(double interest_income, int *is_eligible);
int tsfi_mf_imf_verify_eitc_income_limit(double earned_income, int child_count, int filing_status, int *is_eligible);
int tsfi_mf_imf_verify_capital_loss_cap(double claimed_loss, int filing_status, int *is_valid);
int tsfi_mf_imf_check_student_loan_phaseout(double agi, int filing_status, int *is_below_threshold);
int tsfi_mf_imf_verify_eitc_investment_income(double interest_income, double dividend_income, int *is_eligible);
int tsfi_mf_imf_verify_simple_ira_contribution(double elective_contribution, int *is_valid);
int tsfi_mf_imf_check_actc_income_floor(double earned_income, int *is_above_floor);
int tsfi_mf_imf_verify_simple_ira_match(double employee_comp, double claimed_match, int *is_valid);
int tsfi_mf_imf_verify_adoption_credit(double claimed_credit, int *is_valid);
int tsfi_mf_imf_verify_educator_expense(double claimed_deduction, int is_spouse_educator, int *is_valid);
int tsfi_mf_imf_verify_lifetime_learning_credit(double claimed_credit, int *is_valid);
int tsfi_mf_imf_check_ctc_phaseout_threshold(double agi, int filing_status, int *is_below_threshold);
int tsfi_mf_imf_verify_zero_rate_capital_gains(double taxable_income, int filing_status, int *qualifies_for_zero_rate);
int tsfi_mf_cade_verify_hoh_dependent(int filing_status, int dependent_count, int *is_valid);
int tsfi_mf_imf_check_ss_high_taxability(double modified_agi, double ss_benefits, int filing_status, int *is_subject_to_85);
int tsfi_mf_imf_match_tax_exempt_interest(double reported_1040, double k1_share, int *is_valid);
int tsfi_mf_imf_verify_fifteen_rate_capital_gains(double taxable_income, int filing_status, int *qualifies_for_fifteen_rate);
int tsfi_mf_cade_verify_mfj_signatures(int filing_status, int spouse_primary_sig, int spouse_secondary_sig, int *is_valid);
int tsfi_mf_imf_verify_twenty_rate_capital_gains(double taxable_income, int filing_status, int *qualifies_for_twenty_rate);
int tsfi_mf_cade_verify_qw_dependent(int filing_status, int dependent_count, int *is_valid);
int tsfi_mf_imf_verify_section179_limit(double claimed_deduction, int *is_valid);
int tsfi_mf_cade_verify_mfs_spouse_name(int filing_status, const char *spouse_first_name, const char *spouse_last_name, int *is_valid);
int tsfi_mf_imf_check_section179_phaseout(double total_property_cost, int *is_above_threshold);
int tsfi_mf_cade_check_foreign_account_indicator(double total_interest_dividends, int foreign_disclosure_flag, int *is_valid);
int tsfi_mf_imf_calculate_section179_reduced_limit(double total_property_cost, double *reduced_limit);
int tsfi_mf_cade_match_schedule_b_interest(const double *sources, int source_count, double total_1040_interest, int *is_valid);
int tsfi_mf_cade_match_schedule_b_dividends(const double *sources, int source_count, double total_1040_dividends, int *is_valid);
int tsfi_mf_imf_verify_qss_filing_year(int death_year, int tax_year, int *is_valid);
int tsfi_mf_imf_verify_section1244_loss(double claimed_loss, int filing_status, int *is_valid);
int tsfi_mf_cade_verify_seller_financed_ssn(int is_seller_financed, const char *buyer_ssn, int *is_valid);
int tsfi_mf_cade_verify_seller_financed_address(int is_seller_financed, const char *buyer_address, int *is_valid);
int tsfi_mf_cade_match_foreign_dividends(const double *sources, int source_count, double total_foreign_dividends, int *is_valid);
int tsfi_mf_cade_verify_foreign_trust_indicator(int has_foreign_account, int has_foreign_trust_disclosure, int *is_valid);
int tsfi_mf_imf_verify_section1244_excess_redirection(double total_claimed_loss, int filing_status, double reported_ordinary_loss, double reported_capital_loss, int *is_valid);
int tsfi_mf_cade_verify_seller_financed_ssn_format(const char *ssn, int *is_valid);
int tsfi_mf_imf_verify_section179_income_limit(double claimed_deduction, double net_business_income, int *is_valid);
int tsfi_mf_cade_verify_foreign_country_code(int has_foreign_account, const char *country_code, int *is_valid);
int tsfi_mf_imf_match_k1_dividends(double reported_1040_dividends, double k1_share_dividends, int *is_valid);
int tsfi_mf_cade_verify_foreign_account_consistency(int has_foreign_account, const char *country_code, int *is_valid);
int tsfi_mf_imf_match_k1_capital_gains(double reported_1040_capital_gains, double k1_share_capital_gains, int *is_valid);
int tsfi_mf_cade_verify_div_payer_tin(const char *tin, int *is_valid);
int tsfi_mf_imf_match_k1_interest(double reported_1040_interest, double k1_share_interest, int *is_valid);
int tsfi_mf_cade_verify_div_recipient_tin(const char *tin, int *is_valid);
int tsfi_mf_cade_verify_distinct_ssns(const char *primary_ssn, const char *secondary_ssn, int filing_status, int *is_valid);
int tsfi_mf_cade_verify_int_payer_tin(const char *tin, int *is_valid);
int tsfi_mf_cade_verify_int_recipient_tin(const char *tin, int *is_valid);
int tsfi_mf_imf_verify_reclassified_dividends(double interest_input, double dividend_input, double reclassified_amount, double *final_interest, double *final_dividend);
int tsfi_mf_cade_verify_joint_secondary_signature(int filing_status, int secondary_signature_flag, int *is_valid);
int tsfi_mf_cade_verify_div_payer_address(const char *address, int *is_valid);
int tsfi_mf_cade_verify_int_payer_address(const char *address, int *is_valid);
int tsfi_mf_cade_verify_div_recipient_name(const char *name, int *is_valid);
int tsfi_mf_cade_verify_int_recipient_name(const char *name, int *is_valid);
int tsfi_mf_nato_verify_stanag5066_header(const unsigned char *header, int header_len, int *is_valid);
int tsfi_mf_nato_verify_kermit_payload(const unsigned char *payload, int payload_len, int *is_valid);
int tsfi_mf_nato_verify_cpdu_type(int cpdu_type, int *is_valid);
int tsfi_mf_nato_verify_segment_size(int segment_size, int *is_valid);
int tsfi_mf_nato_verify_sap_number(int sap_number, int *is_valid);
int tsfi_mf_nato_verify_arq_window(int window_size, int *is_valid);
int tsfi_mf_nato_verify_priority_level(int priority, int *is_valid);
int tsfi_mf_nato_match_sync_sequence(int sync_seq, int *is_valid);
int tsfi_mf_nato_verify_cpdu_length(int length, int *is_valid);
int tsfi_mf_nato_verify_tx_mode(int mode, int *is_valid);
int tsfi_mf_nato_verify_short_tin(int address, int *is_valid);
int tsfi_mf_nato_verify_segment_offset(int offset, int segment_size, int total_size, int *is_valid);
int tsfi_mf_cross_verify_tin_isolation(const char *irs_tin, int *is_isolated);
int tsfi_mf_nato_verify_sap_priority(int sap, int priority, int *is_valid);
int tsfi_mf_nato_verify_frame_sequence(int current_seq, int next_seq, int *is_valid);
int tsfi_mf_nato_verify_data_rate(int rate, int *is_valid);
int tsfi_mf_nato_verify_retry_limit(int retries, int *is_valid);
int tsfi_mf_nato_verify_interface_version(int version, int *is_valid);
int tsfi_mf_nato_verify_fcs_type(int fcs_type, int *is_valid);
int tsfi_mf_nato_verify_handshake_confirmation(int status, int *is_valid);
int tsfi_mf_nato_verify_burst_limit(int segment_count, int *is_valid);
int tsfi_mf_nato_verify_flow_direction(int direction, int *is_valid);
int tsfi_mf_nato_verify_multiscan_mode(int mode, int *is_valid);
int tsfi_mf_nato_verify_data_type(int type, int *is_valid);
int tsfi_mf_nato_verify_compression_mode(int mode, int *is_valid);
int tsfi_mf_nato_verify_flow_control(int state, int *is_valid);
int tsfi_mf_nato_verify_delivery_confirmation(int mode, int *is_valid);
int tsfi_mf_nato_verify_backpressure_timeout(int timeout, int *is_valid);
int tsfi_mf_nato_verify_max_frame_size(int frame_size, int *is_valid);
int tsfi_mf_nato_verify_buffer_size(int size, int *is_valid);
int tsfi_mf_nato_verify_segment_lifetime(int lifetime, int *is_valid);
int tsfi_mf_nato_verify_rejection_reason(int reason, int *is_valid);
int tsfi_mf_nato_verify_packet_delay(int delay, int *is_valid);
int tsfi_mf_nato_verify_high_water_mark(int percentage, int *is_valid);
int tsfi_mf_nato_verify_retransmit_timeout(int timeout, int *is_valid);
int tsfi_mf_nato_verify_low_water_mark(int percentage, int *is_valid);
int tsfi_mf_nato_verify_multiscan_frame_count(int count, int *is_valid);
int tsfi_mf_nato_verify_idle_timeout(int timeout, int *is_valid);
int tsfi_mf_nato_verify_delay_interval(int interval, int *is_valid);
int tsfi_mf_nato_verify_low_water_mode(int mode, int *is_valid);
int tsfi_mf_nato_verify_adaptation_mode(int mode, int *is_valid);
int tsfi_mf_nato_verify_subnetwork_profile(int profile, int *is_valid);
int tsfi_mf_nato_verify_retry_delay(int delay_ms, int *is_valid);
int tsfi_mf_nato_verify_profile_override(int flag, int *is_valid);
int tsfi_mf_nato_verify_backoff_multiplier(int multiplier, int *is_valid);
int tsfi_mf_nato_verify_broadcast_address(int address, int *is_valid);
int tsfi_mf_nato_verify_broadcast_window(int mode, int window_size, int *is_valid);
int tsfi_mf_nato_verify_broadcast_backoff_limit(int limit, int *is_valid);
int tsfi_mf_nato_verify_broadcast_queue_capacity(int capacity, int *is_valid);
int tsfi_mf_nato_verify_backoff_algorithm(int algorithm, int *is_valid);
int tsfi_mf_nato_verify_channel_busy_threshold(int threshold_dbm, int *is_valid);
int tsfi_mf_nato_verify_channel_free_threshold(int threshold_dbm, int *is_valid);
int tsfi_mf_nato_verify_broadcast_repeats(int repeats, int *is_valid);
int tsfi_mf_nato_verify_collision_clear_wait(int wait_ms, int *is_valid);
int tsfi_mf_nato_verify_broadcast_guard_time(int guard_ms, int *is_valid);
int tsfi_mf_nato_verify_guard_time_flag(int flag, int *is_valid);
int tsfi_mf_nato_verify_broadcast_expiry(int expiry_sec, int *is_valid);
int tsfi_mf_nato_verify_busy_detection_timeout(int timeout_sec, int *is_valid);
int tsfi_mf_nato_verify_channel_quality(int quality, int *is_valid);
int tsfi_mf_nato_verify_backoff_jitter(int jitter_pct, int *is_valid);
int tsfi_mf_nato_verify_guard_band(int spacing_ms, int *is_valid);
int tsfi_mf_nato_verify_signal_ramp(int ramp_ms, int *is_valid);
int tsfi_mf_nato_verify_rssi_drop(int drop_db, int *is_valid);
int tsfi_mf_nato_verify_backoff_cap(int cap, int *is_valid);
int tsfi_mf_nato_verify_rssi_hysteresis(int hysteresis_db, int *is_valid);
int tsfi_mf_nato_verify_busy_hysteresis_time(int hysteresis_ms, int *is_valid);
int tsfi_mf_nato_verify_rssi_drop_time(int drop_ms, int *is_valid);
int tsfi_mf_nato_verify_busy_samples(int samples, int *is_valid);
int tsfi_mf_nato_verify_rssi_drop_samples(int samples, int *is_valid);
int tsfi_mf_nato_verify_backoff_lfsr_size(int bits, int *is_valid);
int tsfi_mf_nato_verify_status_interval(int interval_sec, int *is_valid);
int tsfi_mf_nato_verify_up_ramp_rate(int rate_db, int *is_valid);
int tsfi_mf_nato_verify_down_ramp_rate(int rate_db, int *is_valid);
int tsfi_mf_nato_verify_backoff_base(int base, int *is_valid);
int tsfi_mf_nato_verify_busy_decay_rate(int rate_db, int *is_valid);
int tsfi_mf_nato_verify_backoff_scale(int scale_ms, int *is_valid);
int tsfi_mf_nato_verify_busy_hysteresis_threshold(int threshold_dbm, int *is_valid);
int tsfi_mf_nato_verify_jitter_dist(int dist, int *is_valid);
int tsfi_mf_nato_verify_up_ramp_duration(int duration_ms, int *is_valid);
int tsfi_mf_nato_verify_slot_map(int map, int *is_valid);
int tsfi_mf_nato_verify_down_ramp_duration(int duration_ms, int *is_valid);
int tsfi_mf_nato_verify_slot_duration(int duration_ms, int *is_valid);
int tsfi_mf_nato_verify_up_ramp_samples(int samples, int *is_valid);
int tsfi_mf_nato_verify_slot_offset(int offset_ms, int *is_valid);
int tsfi_mf_nato_verify_down_ramp_samples(int samples, int *is_valid);
int tsfi_mf_nato_verify_slot_method(int method, int *is_valid);
int tsfi_mf_nato_verify_up_ramp_rate_threshold(int rate_db, int *is_valid);
int tsfi_mf_nato_verify_down_ramp_rate_threshold(int rate_db, int *is_valid);
int tsfi_mf_nato_verify_slot_boundary(int boundary_ms, int *is_valid);
int tsfi_mf_nato_verify_slot_clock_source(int source, int *is_valid);
int tsfi_mf_nato_verify_up_ramp_rate_factor(int factor, int *is_valid);
int tsfi_mf_nato_verify_down_ramp_rate_factor(int factor, int *is_valid);
int tsfi_mf_nato_verify_slot_method_option(int option, int *is_valid);
int tsfi_mf_nato_verify_slot_boundary_option(int option, int *is_valid);
int tsfi_mf_nato_verify_up_ramp_rate_limit(int limit_db, int *is_valid);
int tsfi_mf_nato_verify_down_ramp_rate_limit(int limit_db, int *is_valid);
int tsfi_mf_nato_verify_slot_offset_boundary(int boundary_ms, int *is_valid);
int tsfi_mf_nato_verify_slot_boundary_source(int source, int *is_valid);
int tsfi_mf_nato_verify_up_ramp_rate_factor_offset(int offset_db, int *is_valid);
int tsfi_mf_nato_verify_down_ramp_rate_factor_offset(int offset_db, int *is_valid);
int tsfi_mf_nato_verify_slot_boundary_selector(int selector, int *is_valid);
int tsfi_mf_nato_verify_slot_boundary_source_offset(int offset_ms, int *is_valid);
int tsfi_mf_nato_verify_up_ramp_duration_threshold(int duration_ms, int *is_valid);
int tsfi_mf_nato_verify_down_ramp_duration_threshold(int duration_ms, int *is_valid);
int tsfi_mf_nato_verify_slot_boundary_source_offset_limit(int limit_ms, int *is_valid);

#endif // TSFI_CADE_IMF_H
