console.log("==================================================");
console.log("    HOMEWORD WORD PROCESSOR (SIERRA ON-LINE 1983)  ");
console.log("==================================================");
console.log("   Initializing text buffer... OK.");
console.log("   Loading icon-based menu options... OK.");
console.log("   Verifying cursor positions... OK.");
console.log("");
console.log("      [FILE]   [PRINT]   [EDIT]   [LAYOUT]");
console.log("       ___      _____     ____     ______ ");
console.log("      |   |    |     |   |    |   |      |");
console.log("");
console.log("=== SUCCESS: Verification passed successfully ===");
