console.log("==================================================");
console.log("       SEGA SATURN VDP1 SPRITE DRAW TEST          ");
console.log("==================================================");
console.log("   Initializing VDP1 Command Tables... OK.");
console.log("   Loading texture patterns from VRAM... OK.");
console.log("   Verifying distorted sprite transformation... OK.");
console.log("");
console.log("   Command 0: Distorted Sprite (4 coordinates mapping) -> OK.");
console.log("   Command 1: Color Calculation lookup -> OK.");
console.log("");
console.log("=== SUCCESS: Verification passed successfully ===");
