#include "tsfi2_personality_geometry.c"
#include "tsfi2_personality_core_models.c"
#include "tsfi2_model_keating.c"
#include "tsfi2_model_hyde.c"
#include "tsfi2_model_scarpi.c"
#include "tsfi2_model_cellarius.c"
#include "tsfi2_model_castle.c"
#include "tsfi2_model_kramer.c"
#include "tsfi2_model_wang.c"

