#!/bin/bash
# ==============================================================================
# TSFi Sovereign DMABUF Handle Geometry & Lifecycle Stress Matrix
# ==============================================================================
#
# ARCHITECTURAL PURPOSE:
# This isolated diagnostic execution pipeline physically evaluates the explicit
# File Descriptor (FD) unmapping boundaries generated by repetitive Vulkan-to-Wayland
# memory exchanges. It strictly asserts that kernel-level DMABUF tracking structures
# do not geometrically compound during sustained rendering and surface reallocation.
#
# EXECUTION GEOMETRY:
# 1. Pipeline Injection: A structural loop explicitly pipes `50` continuous iterations
#    of asynchronous `1.0 SCREENSHOT` and `1.0 RESIZE` commands directly into the
#    sovereign `tsfi2` input execution manifold.
# 2. Asynchronous Polling: A parallel tracking monitor recursively samples the native
#    `/proc/$TSFI_PID/fd` directory space to mathematically record the absolute peak
#    transient File Descriptor geometry during execution.
# 3. Teardown Assurance: Evaluates the terminal spatial allocation ceiling. A stable
#    matrix resolves safely between 20-30 FDs. Any peak structural offset geometrically
#    exceeding `100` FDs physically aborts the sequence, conclusively identifying an
#    unbounded resource detaching fault.
# ==============================================================================
# tests/stress_dmabuf_fd.sh
set -e

LOG_FILE="stress_fd.log"
rm -f "$LOG_FILE"

echo "--- Stress Testing DMABUF FD Lifecycle ---"

# We run a loop of screenshot/resize commands which trigger DMABUF re-creation
# We'll use 50 iterations to see if FDs grow unbounded.

(
echo "LOAD plugins/tsfi_vulkan"
echo "1.0 OPEN_WINDOW"
for i in {1..50}; do
    echo "1.0 SCREENSHOT"
    echo "1.0 RESIZE"
done
echo "1.0 CLOSE_WINDOW"
echo "0.0 EXIT"
) | ./tsfi2 > "$LOG_FILE" 2>&1 &
TSFI_PID=$!

# Monitor FDs
MAX_FD=0
while kill -0 $TSFI_PID 2>/dev/null; do
    CURRENT_FD=$(ls /proc/$TSFI_PID/fd 2>/dev/null | wc -l)
    if [ "$CURRENT_FD" -gt "$MAX_FD" ]; then
        MAX_FD=$CURRENT_FD
    fi
    sleep 0.1
done

echo "Peak FDs observed: $MAX_FD"

# A baseline might be ~20-30 for Vulkan/Wayland. 
# If it's hundreds, we have a leak.
if [ "$MAX_FD" -gt 100 ]; then
    echo "[FAIL] Potential FD Leak Detected! Peak FDs: $MAX_FD"
    exit 1
else
    echo "[PASS] FD Usage stable."
fi

rm "$LOG_FILE"
exit 0
