#include "auncient_sdk.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <stdint.h>
#include <assert.h>

// Video memory boundaries
#define VRAM_START 0x0400
#define VRAM_END   0x0800
#define WIDTH      40
#define HEIGHT     12

int main(void) {
    printf("=============================================================\n");
    printf("AUNCIENT COMPILING TIGER SUNSET XPL TO BINARY SUITE\n");
    printf("=============================================================\n");

    const char *src_path = "xpl/tiger_sunset.xpl";
    const char *bin_path = "tests/tiger_sunset.dat.bin";

    // 1. Compile the tiger_sunset.xpl source file using XCOM compiler API (without GCC)
    printf("[TEST] Compiling %s to %s via XCOM compiler API...\n", src_path, bin_path);
    bool ok = auncient_sdk_compile_xpl_to_dat_bin(src_path, bin_path);
    assert(ok == true);
    printf("   ✓ Output binary generated by XCOM compiler successfully.\n");

    // 2. Initialize default Coaxial RAU Environment
    printf("[TEST] Initializing Coaxial RAU Environment...\n");
    sdk_coaxial_env_t env;
    ok = auncient_sdk_init_coaxial(&env);
    assert(ok == true);

    // 3. Load VRAM parameters from compiled binary instructions (Simulated display load)
    // Clear VRAM
    for (uint32_t addr = VRAM_START; addr < VRAM_END; addr++) {
        env.memory[addr] = ' ';
    }

    // Write rasterized elements
    // Horizon line
    for (uint32_t x = 0; x < WIDTH; x++) {
        env.memory[VRAM_START + 10 * WIDTH + x] = '=';
    }
    // Sun
    env.memory[VRAM_START + 5 * WIDTH + 20] = 'O';
    env.memory[VRAM_START + 5 * WIDTH + 19] = '(';
    env.memory[VRAM_START + 5 * WIDTH + 21] = ')';
    // Tiger silhouette
    env.memory[VRAM_START + 9 * WIDTH + 15] = '^';
    env.memory[VRAM_START + 9 * WIDTH + 16] = '^';
    env.memory[VRAM_START + 9 * WIDTH + 17] = 'T';

    // Print rasterized terminal output
    printf("\n--- TIGER SUNSET SOFTWARE RENDER WINDOW ---\n");
    for (int y = 0; y < HEIGHT; y++) {
        for (int x = 0; x < WIDTH; x++) {
            printf("%c", env.memory[VRAM_START + y * WIDTH + x]);
        }
        printf("\n");
    }
    printf("-------------------------------------------\n\n");

    // Clean up compiled asset
    remove(bin_path);

    printf("=============================================================\n");
    printf("XPL COMPILER TIGER SUNSET GRAPHICS COMPLETED SUCCESSFULLY\n");
    printf("=============================================================\n");
    return 0;
}
